In [1]:
import numpy as np

e3 = np.array([1/3, 2/3, 2/3])                       
e1 = np.array([2/np.sqrt(5), -1/np.sqrt(5), 0])      
e2 = np.cross(e3, e1)                                

Q = np.column_stack((e1, e2, e3))                    


A1 = np.array([[0, -1, 0],
               [1,  0, 0],
               [0,  0, 1]])

A = Q @ A1 @ Q.T

np.set_printoptions(suppress=True, precision=10)
print("e2 = \n",e2)

print("Q =\n", Q)
print("\nA =\n", A)

print("\nA * 9 ≈\n", 9*A)

axis = np.array([1,2,2])
print("\nA @ axis =\n", A @ axis)


e2 = 
 [ 0.298142397   0.596284794  -0.7453559925]
Q =
 [[ 0.894427191   0.298142397   0.3333333333]
 [-0.4472135955  0.596284794   0.6666666667]
 [ 0.           -0.7453559925  0.6666666667]]

A =
 [[ 0.1111111111 -0.4444444444  0.8888888889]
 [ 0.8888888889  0.4444444444  0.1111111111]
 [-0.4444444444  0.7777777778  0.4444444444]]

A * 9 ≈
 [[ 1. -4.  8.]
 [ 8.  4.  1.]
 [-4.  7.  4.]]

A @ axis =
 [1. 2. 2.]


In [11]:
e3 = np.array([1, 1, 1])                       
e1 = np.array([-1, 1, 0])      
e2 = np.cross(e3, e1)                                

# Normalise
e1 = e1 / np.linalg.norm(e1)
e3 = e3 / np.linalg.norm(e3)
e2 = e2 / np.linalg.norm(e2)
                         
Q = np.column_stack((e1, e2, e3))
print(np.allclose(Q.T, np.linalg.inv(Q))) 

True


array([-1,  1,  0])